export const SET_CATEGORIES_LIST = "SET_CATEGORIES_LIST";
export const SET_CATEGORIES_LIST_SUCCESS = "SET_CATEGORIES_LIST_SUCCESS";
export const SET_CATEGORIES_LIST_ERROR = "SET_CATEGORIES_LIST_ERROR";

export const SET_CATEGORY = "SET_CATEGORY";
export const SET_CATEGORY_SUCCESS = "SET_CATEGORY_SUCCESS";
export const SET_CATEGORY_ERROR = "SET_CATEGORY_ERROR";

export const SET_ADD_CATEGORY = "SET_ADD_CATEGORY";
export const SET_ADD_CATEGORY_SUCCESS = "SET_ADD_CATEGORY_SUCCESS";
export const SET_ADD_CATEGORY_ERROR = "SET_ADD_CATEGORY_ERROR";

export const SET_UPDATE_CATEGORY = "SET_UPDATE_CATEGORY";
export const SET_UPDATE_CATEGORY_SUCCESS = "SET_UPDATE_CATEGORY_SUCCESS";
export const SET_UPDATE_CATEGORY_ERROR = "SET_UPDATE_CATEGORY_ERROR";

export const SET_DELETE_CATEGORY = "SET_DELETE_CATEGORY";
export const SET_DELETE_CATEGORY_SUCCESS = "SET_DELETE_CATEGORY_SUCCESS";
export const SET_DELETE_CATEGORY_ERROR = "SET_DELETE_CATEGORY_ERROR";

export const SET_UPLOAD_CATEGORY_PICTURE = "SET_UPLOAD_CATEGORY_PICTURE";
export const SET_UPLOAD_CATEGORY_PICTURE_SUCCESS =
  "SET_UPLOAD_CATEGORY_PICTURE_SUCCESS";
export const SET_UPLOAD_CATEGORY_PICTURE_ERROR =
  "SET_UPLOAD_CATEGORY_PICTURE_ERROR";
