export const SET_UPLOAD_CATEGORY_PICTURE = "SET_UPLOAD_CATEGORY_PICTURE";
export const SET_UPLOAD_CATEGORY_PICTURE_SUCCESS = "SET_UPLOAD_CATEGORY_PICTURE_SUCCESS";
export const SET_UPLOAD_CATEGORY_PICTURE_ERROR = "SET_UPLOAD_CATEGORY_PICTURE_ERROR";

export const SET_DELETE_CATEGORY_PICTURE = "SET_DELETE_CATEGORY_PICTURE";
export const SET_DELETE_CATEGORY_PICTURE_SUCCESS = "SET_DELETE_CATEGORY_PICTURE_SUCCESS";
export const SET_DELETE_CATEGORY_PICTURE_ERROR = "SET_DELETE_CATEGORY_PICTURE_ERROR";

